steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-north2-docker.pkg.dev/logical-sled-473014-i0/my-docker-repo/my-app-image:latest', '.']
options:
  logging: CLOUD_LOGGING_ONLY